version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    groups:
      opentelemetry:
        patterns: ["opentelemetry*", "tracing-opentelemetry"]
      minor-and-patch:
        update-types: [minor, patch]
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
